version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - messagehub-network

  backend:
    build: .
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo-container:27017/chatdb
    networks:
      - messagehub-network
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - messagehub-network
    depends_on:
      - backend

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data: