# 3. backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: thedevsami/messagehub:backend-latest
          ports:
            - containerPort: 5000
          env:
            # MongoDB connection
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-urls
                  key: MONGODB_URL
            # Allow CORS from both internal and external frontend URLs
            - name: CORS_ORIGIN
              value: "http://frontend-service:3000"
            # Port configuration
            - name: PORT
              value: "5000"
            # Public URL for email verification links
            - name: PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: app-urls
                  key: BACKEND_EXTERNAL_URL
---
# Backend Service for API access
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30081  # Fixed NodePort for backend access
