# 2. frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: thedevsami/messagehub:frontend-latest
          ports:
            - containerPort: 3000
          env:
            # URL for making API calls to backend
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-urls
                  key: BACKEND_EXTERNAL_URL
            # URL for email verification links
            - name: LOCALHOST
              valueFrom:
                configMapKeyRef:
                  name: app-urls
                  key: FRONTEND_EXTERNAL_URL
---
# Frontend Service for exposing the React app
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080  # Fixed NodePort for frontend access
